### PR TITLE
Update update.sh

### PR DESCRIPTION
**Pull request by globalcontrolseg**
## Status
**READY/IN DEVELOPMENT/HOLD**

## Migrations
YES | NO

## Description
A few sentences describing the overall goals of the pull request's commits.

## Related PRs
List related PRs against other branches:

branch | PR
------ | ------
other_pr_production | [link]()
other_pr_master | [link]()

## Todos
- [x] Tests
- [x] Documentation

## Deploy Notes
Notes regarding deployment the contained body of work.  These should note any
db migrations, etc.

## Steps to Test or Reproduce
Outline the steps to test or reproduce the PR here.

```sh
git pull --prune
git checkout <feature_branch>
bundle; script/server
```

1. 

## Impacted Areas in Application
List general components of the application that this PR will affect:

*

### CODE REVIEW

**Review by globalcontrolseg — COMMENTED** [review]
diretório inexistente

**Comment by magnussolution** [comment]
what operating system do you use?

**Comment by globalcontrolseg** [comment]
Debian 9.12 stretch

**Comment by magnussolution** [comment]
We only use CENTOS, so we not make testes on DEBIAN.

You can edit your pull request and make this way

```
 if [ ${DIST} = "DEBIAN" ]; then
 chown -R asterisk:asterisk /var/lib/php/sessions/
elif [ ${DIST} = "CENTOS" ]; then  
  chown -R asterisk:asterisk /var/lib/php/session/
fi
```

**Comment by magnussolution** [comment]
i update the install.sh chech the commit https://github.com/magnussolution/magnusbilling7/commit/1aa14d8744e6da483ba3349f6c840da83097ef15

**Pull request closed without merging**
